query GET_WEATHER($localizacao: String!, $collectionHot: String!, $collectionCold: String!) {
  weather(localizacao: $localizacao, collectionHot: $collectionHot,collectionCold: $collectionCold) {
    link,
    clima,
    promotion
  }
}
